# Generated by Django 4.2.11 on 2024-11-18 01:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, null=True, verbose_name='user level'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_progress',
            field=models.IntegerField(default=0, null=True, verbose_name='user level progress'),
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_group_name', models.CharField(max_length=10, null=True)),
                ('app_tokens', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), blank=True, null=True, size=None), blank=True, default=list, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackToLife_App.user')),
            ],
        ),
    ]
