# Generated by Django 4.2.11 on 2024-11-18 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0002_user_level_user_level_progress_blockgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroup',
            name='app_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=260), blank=True, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
