# Generated by Django 4.2.11 on 2024-11-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0004_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='length',
            new_name='time_length',
        ),
    ]
