# Generated by Django 4.2.11 on 2024-11-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0006_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=16, null=True, unique=True),
        ),
    ]
