# Generated by Django 4.2.11 on 2024-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0007_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True, verbose_name='text count')),
                ('active', models.BooleanField(default=False, verbose_name='active tracker')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='p_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='p_code_time',
            field=models.DateTimeField(null=True, verbose_name='phone code time added'),
        ),
    ]
