# Generated by Django 4.2.11 on 2024-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackToLife_App', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='locked',
            field=models.BooleanField(default=False, null=True, verbose_name='block lock'),
        ),
    ]
